# Generated by Django 5.1.7 on 2025-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customuser_birthdate_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('blacklist_status', models.BooleanField(default=False)),
                ('registration_validity_date', models.DateField()),
                ('puc_validity_date', models.DateField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
