# Generated by Django 5.1.7 on 2025-03-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalized_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_by', to='myapp.vehicle')),
            ],
            options={
                'verbose_name': 'Personalized Vehicle',
                'verbose_name_plural': 'Personalized Vehicles',
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
