# Generated by Django 5.1.7 on 2025-03-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_personalizedvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('Speeding', 'Speeding'), ('Parking', 'Illegal Parking'), ('Documentation', 'Missing Documentation'), ('Signal', 'Signal Violation'), ('Emission', 'Emission Standards'), ('License', 'License Related'), ('Registration', 'Registration Related'), ('Insurance', 'Insurance Related'), ('Other', 'Other Violation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposed_date', models.DateTimeField()),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Contested', 'Contested'), ('Waived', 'Waived')], default='Unpaid', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('imposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposed_modern_fines', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_fines', to='myapp.vehicle')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'ordering': ['-imposed_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('Speeding', 'Speeding'), ('No Parking', 'No Parking'), ('Wrong Side Driving', 'Wrong Side Driving'), ('No Helmet', 'No Helmet'), ('No Seatbelt', 'No Seatbelt'), ('Invalid Documents', 'Invalid Documents'), ('Signal Jumping', 'Signal Jumping'), ('Overloading', 'Overloading'), ('Invalid Number Plate', 'Invalid Number Plate'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imposed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Contested', 'Contested'), ('Waived', 'Waived')], default='Unpaid', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('imposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposed_fines', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='myapp.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Fine',
                'verbose_name_plural': 'Vehicle Fines',
                'ordering': ['-imposed_date'],
            },
        ),
    ]
