# Generated by Django 5.1.7 on 2025-03-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_vehiclefine_violation_image_and_more'),
    ]

    operations = [
    ]
