# Generated by Django 5.1.7 on 2025-03-30 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passwordresetverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetverification',
            old_name='is_verified',
            new_name='is_used',
        ),
        migrations.AlterField(
            model_name='passwordresetverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
