# Generated by Django 5.1.7 on 2025-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_personalizedvehicle_puc_expiry_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedvehicle',
            name='puc_expiry_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if notification has been sent for PUC expiry'),
        ),
        migrations.AlterField(
            model_name='personalizedvehicle',
            name='registration_expiry_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if notification has been sent for registration expiry'),
        ),
        migrations.AddIndex(
            model_name='personalizedvehicle',
            index=models.Index(fields=['user', 'vehicle'], name='myapp_perso_user_id_a239ed_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedvehicle',
            index=models.Index(fields=['registration_expiry_notified'], name='myapp_perso_registr_1f2fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedvehicle',
            index=models.Index(fields=['puc_expiry_notified'], name='myapp_perso_puc_exp_1b0153_idx'),
        ),
    ]
