# Generated by Django 4.2.18 on 2025-04-04 10:34

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_vehiclefine_violation_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myapp.models.violation_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.vehiclefine')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
