# Generated by Django 4.2.18 on 2025-04-04 17:56

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_violationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.user_profile_picture_path),
        ),
    ]
