# Generated by Django 4.2.18 on 2025-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customuser_profile_picture'),
    ]

    operations = [
    ]
