# Generated by Django 4.2.18 on 2025-04-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_add_profile_picture_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the RTO office where the vehicle was registered', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2-wheeler', '2-wheeler'), ('3-wheeler', '3-wheeler'), ('4-wheeler', '4-wheeler'), ('public-transport', 'Public Transport'), ('heavy-vehicle', 'Heavy Vehicle (Truck etc)')], default='4-wheeler', max_length=20),
        ),
    ]
